import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Button from "../components/Button";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>먹보닷컴</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button type="primary">
          primary
        </Button>
        <Button type="default">
          default
        </Button>
        <Button type="white">
          white
        </Button>
      </div>
    </div>
  )
}

export default Home
